# Site Settings
title: Your Name
description: Your Name - Projects and CV 

# IMPORTANT: This matches your specific repository name
baseurl: "/sp26-portfolio-cwr53" 
url: "https://cornell-mae-ug.github.io"

# Theme Settings
theme: jekyll-theme-minimal

# This simplifies your URLs so /projects/filename works
permalink: /:path/

# Markdown Settings
markdown: kramdown
kramdown:
  input: GFM

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
